# General
FOX_TARGET_DEVICES="salaa"
FOX_BUILD_TYPE="Stable"
FOX_MAINTAINER_PATCH_VERSION=$(date +"%Y%m%d")
OF_MAINTAINER=LUKS
OF_MAINTAINER_AVATAR=0
TARGET_DEVICE_ALT="RMX2151,RMX2151L1,RMX2155,RMX2155L1,RMX2156L1,RMX2161L1,RMX2163L1,salaa"

# Device Variant
FOX_ARCH=arm64
FOX_VARIANT="RUI_V3.0"

# Funtions
FOX_REPLACE_TOOLBOX_GETPROP=1
FOX_USE_TAR_BINARY=1
FOX_USE_SED_BINARY=1
FOX_USE_BASH_SHELL=1
FOX_ASH_IS_BASH=1
FOX_USE_GREP_BINARY=1
FOX_USE_XZ_UTILS=1
FOX_USE_NANO_EDITOR=1
FOX_USE_PATCHELF_BINARY=1
FOX_USE_FSCK_EROFS_BINARY=1
FOX_USE_DATA_RECOVERY_FOR_SETTINGS=1
FOX_BASH_TO_SYSTEM_BIN=1
OF_ENABLE_LPTOOLS=1
OF_ADVANCED_SECURITY=1
OF_CHECK_OVERWRITE_ATTEMPTS=1
OF_USE_MAGISKBOOT=1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
OF_FLASHLIGHT_ENABLE=0
OF_FL_PATH1="/sys/class/flashlight/mt-flash-led1"
OF_FL_PATH2="/sys/class/flashlight/mt-flash-led2"
OF_FORCE_CASEFOLDING=1
OF_USE_DMCTL=1
OF_ENABLE_FRP_ADDON=1

# Display Settings
OF_SCREEN_H=2400
OF_STATUS_H=115
OF_STATUS_INDENT_LEFT=155
OF_STATUS_INDENT_RIGHT=46
OF_HIDE_NOTCH=1
OF_ALLOW_DISABLE_NAVBAR=0
OF_USE_GREEN_LED=0
OF_DEFAULT_TIMEZONE="SAUST-3;SAUDT"

# Splash image size (max 130 KB)
OF_SPLASH_MAX_SIZE=130

# Other OrangeFox Vars
FOX_ENABLE_APP_MANAGER=1
FOX_USE_SPECIFIC_MAGISK_ZIP="/home/luks/OrangeFox_sync/fox_12.1/device/realme/salaa/Magisk/Magisk-v30.6.zip"
FOX_BUGGED_AOSP_ARB_WORKAROUND="1616300800"  # Sun 21 Mar 04:26:40 GMT 2021
FOX_REMOVE_BUSYBOX_BINARY=1
FOX_DELETE_AROMAFM=1
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
FOX_USE_FSCK_EROFS_BINARY=1
OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
OF_TWRP_COMPATIBILITY_MODE=1
OF_SKIP_DECRYPTED_ADOPTED_STORAGE=1
OF_FIX_DECRYPTION_ON_DATA_MEDIA=1
OF_PATCH_AVB20=1
OF_SUPPORT_OZIP_DECRYPTION=1
OF_NO_TREBLE_COMPATIBILITY_CHECK=1
OF_QUICK_BACKUP_LIST="/boot;/dtbo;/recovery;/persist;/nvram;/tee2;/nvdata;/protect_f;/protect_s/"
OF_NO_KEYMASTER_VER_4X=1
OF_DEFAULT_KEYMASTER_VERSION=4.0
OF_USE_LZ4_COMPRESSION=true
OF_UNBIND_SDCARD_F2FS=1
OF_WIPE_METADATA_AFTER_DATAFORMAT=1
OF_UNMOUNT_SDCARDS_BEFORE_REBOOT=1
OF_ENABLE_FS_COMPRESSION=1
OF_FORCE_DATA_FORMAT_F2FS=1

# OTA
OF_DISABLE_MIUI_OTA_BY_DEFAULT=1
OF_NO_MIUI_PATCH_WARNING=1
